//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pomodoro.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        internal static string about_one {
            get {
                return ResourceManager.GetString("about_one", resourceCulture);
            }
        }
        
        internal static string about_two {
            get {
                return ResourceManager.GetString("about_two", resourceCulture);
            }
        }
        
        internal static string about_three {
            get {
                return ResourceManager.GetString("about_three", resourceCulture);
            }
        }
        
        internal static string xamarin_platform {
            get {
                return ResourceManager.GetString("xamarin_platform", resourceCulture);
            }
        }
        
        internal static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        internal static string historical {
            get {
                return ResourceManager.GetString("historical", resourceCulture);
            }
        }
        
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static string start_pause {
            get {
                return ResourceManager.GetString("start_pause", resourceCulture);
            }
        }
        
        internal static string title_error_alert {
            get {
                return ResourceManager.GetString("title_error_alert", resourceCulture);
            }
        }
        
        internal static string configuration_break_duration {
            get {
                return ResourceManager.GetString("configuration_break_duration", resourceCulture);
            }
        }
        
        internal static string message_error_clear_lista {
            get {
                return ResourceManager.GetString("message_error_clear_lista", resourceCulture);
            }
        }
        
        internal static string title_succes {
            get {
                return ResourceManager.GetString("title_succes", resourceCulture);
            }
        }
        
        internal static string title_go_tab_pomodoro {
            get {
                return ResourceManager.GetString("title_go_tab_pomodoro", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string about_project {
            get {
                return ResourceManager.GetString("about_project", resourceCulture);
            }
        }
        
        internal static string about_architecture {
            get {
                return ResourceManager.GetString("about_architecture", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string pomodoro_duration {
            get {
                return ResourceManager.GetString("pomodoro_duration", resourceCulture);
            }
        }
        
        internal static string pomodoro_break {
            get {
                return ResourceManager.GetString("pomodoro_break", resourceCulture);
            }
        }
        
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        internal static string clear_list {
            get {
                return ResourceManager.GetString("clear_list", resourceCulture);
            }
        }
    }
}
